// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/taskflow.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Cores                int32    `protobuf:"varint,4,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory               int64    `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk                 int64    `protobuf:"varint,6,opt,name=disk,proto3" json:"disk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RegisterRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RegisterRequest) GetCores() int32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *RegisterRequest) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *RegisterRequest) GetDisk() int64 {
	if m != nil {
		return m.Disk
	}
	return 0
}

type RegisterResponse struct {
	RunnerId             string   `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetRunnerId() string {
	if m != nil {
		return m.RunnerId
	}
	return ""
}

func (m *RegisterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HeartbeatRequest struct {
	RunnerId             string   `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RunningVms           int32    `protobuf:"varint,3,opt,name=running_vms,json=runningVms,proto3" json:"running_vms,omitempty"`
	RunningTasks         int32    `protobuf:"varint,4,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{2}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetRunnerId() string {
	if m != nil {
		return m.RunnerId
	}
	return ""
}

func (m *HeartbeatRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HeartbeatRequest) GetRunningVms() int32 {
	if m != nil {
		return m.RunningVms
	}
	return 0
}

func (m *HeartbeatRequest) GetRunningTasks() int32 {
	if m != nil {
		return m.RunningTasks
	}
	return 0
}

type HeartbeatResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{3}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CreateVMRequest struct {
	VmId                 string            `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	UserId               string            `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageUrl             string            `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	GitUrl               string            `protobuf:"bytes,4,opt,name=git_url,json=gitUrl,proto3" json:"git_url,omitempty"`
	GitToken             string            `protobuf:"bytes,5,opt,name=git_token,json=gitToken,proto3" json:"git_token,omitempty"`
	Cores                int32             `protobuf:"varint,6,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory               int64             `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	EnvVars              map[string]string `protobuf:"bytes,8,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TtlSeconds           int64             `protobuf:"varint,9,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateVMRequest) Reset()         { *m = CreateVMRequest{} }
func (m *CreateVMRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVMRequest) ProtoMessage()    {}
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{4}
}

func (m *CreateVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVMRequest.Unmarshal(m, b)
}
func (m *CreateVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVMRequest.Marshal(b, m, deterministic)
}
func (m *CreateVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVMRequest.Merge(m, src)
}
func (m *CreateVMRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVMRequest.Size(m)
}
func (m *CreateVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVMRequest proto.InternalMessageInfo

func (m *CreateVMRequest) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *CreateVMRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateVMRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *CreateVMRequest) GetGitUrl() string {
	if m != nil {
		return m.GitUrl
	}
	return ""
}

func (m *CreateVMRequest) GetGitToken() string {
	if m != nil {
		return m.GitToken
	}
	return ""
}

func (m *CreateVMRequest) GetCores() int32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *CreateVMRequest) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *CreateVMRequest) GetEnvVars() map[string]string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *CreateVMRequest) GetTtlSeconds() int64 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

type CreateVMResponse struct {
	VmId                 string   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVMResponse) Reset()         { *m = CreateVMResponse{} }
func (m *CreateVMResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVMResponse) ProtoMessage()    {}
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{5}
}

func (m *CreateVMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVMResponse.Unmarshal(m, b)
}
func (m *CreateVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVMResponse.Marshal(b, m, deterministic)
}
func (m *CreateVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVMResponse.Merge(m, src)
}
func (m *CreateVMResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVMResponse.Size(m)
}
func (m *CreateVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVMResponse proto.InternalMessageInfo

func (m *CreateVMResponse) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *CreateVMResponse) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *CreateVMResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateVMResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteVMRequest struct {
	VmId                 string   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	RunnerId             string   `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVMRequest) Reset()         { *m = DeleteVMRequest{} }
func (m *DeleteVMRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVMRequest) ProtoMessage()    {}
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{6}
}

func (m *DeleteVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVMRequest.Unmarshal(m, b)
}
func (m *DeleteVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVMRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVMRequest.Merge(m, src)
}
func (m *DeleteVMRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVMRequest.Size(m)
}
func (m *DeleteVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVMRequest proto.InternalMessageInfo

func (m *DeleteVMRequest) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *DeleteVMRequest) GetRunnerId() string {
	if m != nil {
		return m.RunnerId
	}
	return ""
}

type DeleteVMResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVMResponse) Reset()         { *m = DeleteVMResponse{} }
func (m *DeleteVMResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVMResponse) ProtoMessage()    {}
func (*DeleteVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{7}
}

func (m *DeleteVMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVMResponse.Unmarshal(m, b)
}
func (m *DeleteVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVMResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVMResponse.Merge(m, src)
}
func (m *DeleteVMResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVMResponse.Size(m)
}
func (m *DeleteVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVMResponse proto.InternalMessageInfo

func (m *DeleteVMResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteVMResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListVMsRequest struct {
	RunnerId             string   `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVMsRequest) Reset()         { *m = ListVMsRequest{} }
func (m *ListVMsRequest) String() string { return proto.CompactTextString(m) }
func (*ListVMsRequest) ProtoMessage()    {}
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{8}
}

func (m *ListVMsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVMsRequest.Unmarshal(m, b)
}
func (m *ListVMsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVMsRequest.Marshal(b, m, deterministic)
}
func (m *ListVMsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVMsRequest.Merge(m, src)
}
func (m *ListVMsRequest) XXX_Size() int {
	return xxx_messageInfo_ListVMsRequest.Size(m)
}
func (m *ListVMsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVMsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVMsRequest proto.InternalMessageInfo

func (m *ListVMsRequest) GetRunnerId() string {
	if m != nil {
		return m.RunnerId
	}
	return ""
}

type ListVMsResponse struct {
	Vms                  []*VMInfo `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListVMsResponse) Reset()         { *m = ListVMsResponse{} }
func (m *ListVMsResponse) String() string { return proto.CompactTextString(m) }
func (*ListVMsResponse) ProtoMessage()    {}
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{9}
}

func (m *ListVMsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVMsResponse.Unmarshal(m, b)
}
func (m *ListVMsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVMsResponse.Marshal(b, m, deterministic)
}
func (m *ListVMsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVMsResponse.Merge(m, src)
}
func (m *ListVMsResponse) XXX_Size() int {
	return xxx_messageInfo_ListVMsResponse.Size(m)
}
func (m *ListVMsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVMsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVMsResponse proto.InternalMessageInfo

func (m *ListVMsResponse) GetVms() []*VMInfo {
	if m != nil {
		return m.Vms
	}
	return nil
}

type GetVMInfoRequest struct {
	VmId                 string   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVMInfoRequest) Reset()         { *m = GetVMInfoRequest{} }
func (m *GetVMInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetVMInfoRequest) ProtoMessage()    {}
func (*GetVMInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{10}
}

func (m *GetVMInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVMInfoRequest.Unmarshal(m, b)
}
func (m *GetVMInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVMInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetVMInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVMInfoRequest.Merge(m, src)
}
func (m *GetVMInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetVMInfoRequest.Size(m)
}
func (m *GetVMInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVMInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVMInfoRequest proto.InternalMessageInfo

func (m *GetVMInfoRequest) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

type GetVMInfoResponse struct {
	Vm                   *VMInfo  `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVMInfoResponse) Reset()         { *m = GetVMInfoResponse{} }
func (m *GetVMInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetVMInfoResponse) ProtoMessage()    {}
func (*GetVMInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{11}
}

func (m *GetVMInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVMInfoResponse.Unmarshal(m, b)
}
func (m *GetVMInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVMInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetVMInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVMInfoResponse.Merge(m, src)
}
func (m *GetVMInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetVMInfoResponse.Size(m)
}
func (m *GetVMInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVMInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVMInfoResponse proto.InternalMessageInfo

func (m *GetVMInfoResponse) GetVm() *VMInfo {
	if m != nil {
		return m.Vm
	}
	return nil
}

type VMInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VMInfo) Reset()         { *m = VMInfo{} }
func (m *VMInfo) String() string { return proto.CompactTextString(m) }
func (*VMInfo) ProtoMessage()    {}
func (*VMInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{12}
}

func (m *VMInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMInfo.Unmarshal(m, b)
}
func (m *VMInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMInfo.Marshal(b, m, deterministic)
}
func (m *VMInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMInfo.Merge(m, src)
}
func (m *VMInfo) XXX_Size() int {
	return xxx_messageInfo_VMInfo.Size(m)
}
func (m *VMInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VMInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VMInfo proto.InternalMessageInfo

func (m *VMInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VMInfo) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *VMInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VMInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type CreateTaskRequest struct {
	TaskId               string            `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VmId                 string            `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Text                 string            `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Model                string            `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey               string            `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl              string            `protobuf:"bytes,6,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	EnvVars              map[string]string `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{13}
}

func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (m *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(m, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *CreateTaskRequest) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *CreateTaskRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CreateTaskRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *CreateTaskRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *CreateTaskRequest) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *CreateTaskRequest) GetEnvVars() map[string]string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

type CreateTaskResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskResponse) Reset()         { *m = CreateTaskResponse{} }
func (m *CreateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTaskResponse) ProtoMessage()    {}
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{14}
}

func (m *CreateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskResponse.Unmarshal(m, b)
}
func (m *CreateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskResponse.Marshal(b, m, deterministic)
}
func (m *CreateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskResponse.Merge(m, src)
}
func (m *CreateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTaskResponse.Size(m)
}
func (m *CreateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskResponse proto.InternalMessageInfo

func (m *CreateTaskResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateTaskResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StopTaskRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VmId                 string   `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopTaskRequest) Reset()         { *m = StopTaskRequest{} }
func (m *StopTaskRequest) String() string { return proto.CompactTextString(m) }
func (*StopTaskRequest) ProtoMessage()    {}
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{15}
}

func (m *StopTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopTaskRequest.Unmarshal(m, b)
}
func (m *StopTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopTaskRequest.Marshal(b, m, deterministic)
}
func (m *StopTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopTaskRequest.Merge(m, src)
}
func (m *StopTaskRequest) XXX_Size() int {
	return xxx_messageInfo_StopTaskRequest.Size(m)
}
func (m *StopTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopTaskRequest proto.InternalMessageInfo

func (m *StopTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *StopTaskRequest) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

type StopTaskResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopTaskResponse) Reset()         { *m = StopTaskResponse{} }
func (m *StopTaskResponse) String() string { return proto.CompactTextString(m) }
func (*StopTaskResponse) ProtoMessage()    {}
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{16}
}

func (m *StopTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopTaskResponse.Unmarshal(m, b)
}
func (m *StopTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopTaskResponse.Marshal(b, m, deterministic)
}
func (m *StopTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopTaskResponse.Merge(m, src)
}
func (m *StopTaskResponse) XXX_Size() int {
	return xxx_messageInfo_StopTaskResponse.Size(m)
}
func (m *StopTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopTaskResponse proto.InternalMessageInfo

func (m *StopTaskResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *StopTaskResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TerminalData struct {
	VmId                 string          `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	TerminalId           string          `protobuf:"bytes,2,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Data                 []byte          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Resize               *TerminalResize `protobuf:"bytes,4,opt,name=resize,proto3" json:"resize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TerminalData) Reset()         { *m = TerminalData{} }
func (m *TerminalData) String() string { return proto.CompactTextString(m) }
func (*TerminalData) ProtoMessage()    {}
func (*TerminalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{17}
}

func (m *TerminalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalData.Unmarshal(m, b)
}
func (m *TerminalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalData.Marshal(b, m, deterministic)
}
func (m *TerminalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalData.Merge(m, src)
}
func (m *TerminalData) XXX_Size() int {
	return xxx_messageInfo_TerminalData.Size(m)
}
func (m *TerminalData) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalData.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalData proto.InternalMessageInfo

func (m *TerminalData) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *TerminalData) GetTerminalId() string {
	if m != nil {
		return m.TerminalId
	}
	return ""
}

func (m *TerminalData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TerminalData) GetResize() *TerminalResize {
	if m != nil {
		return m.Resize
	}
	return nil
}

type TerminalResize struct {
	Cols                 uint32   `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows                 uint32   `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalResize) Reset()         { *m = TerminalResize{} }
func (m *TerminalResize) String() string { return proto.CompactTextString(m) }
func (*TerminalResize) ProtoMessage()    {}
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{18}
}

func (m *TerminalResize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalResize.Unmarshal(m, b)
}
func (m *TerminalResize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalResize.Marshal(b, m, deterministic)
}
func (m *TerminalResize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalResize.Merge(m, src)
}
func (m *TerminalResize) XXX_Size() int {
	return xxx_messageInfo_TerminalResize.Size(m)
}
func (m *TerminalResize) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalResize.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalResize proto.InternalMessageInfo

func (m *TerminalResize) GetCols() uint32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func (m *TerminalResize) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

type ReportRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{19}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type ReportEntry struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportEntry) Reset()         { *m = ReportEntry{} }
func (m *ReportEntry) String() string { return proto.CompactTextString(m) }
func (*ReportEntry) ProtoMessage()    {}
func (*ReportEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{20}
}

func (m *ReportEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportEntry.Unmarshal(m, b)
}
func (m *ReportEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportEntry.Marshal(b, m, deterministic)
}
func (m *ReportEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportEntry.Merge(m, src)
}
func (m *ReportEntry) XXX_Size() int {
	return xxx_messageInfo_ReportEntry.Size(m)
}
func (m *ReportEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ReportEntry proto.InternalMessageInfo

func (m *ReportEntry) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ReportEntry) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ReportEntry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ReportEntry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Runner 发送给 Taskflow 的消息
type RunnerMessage struct {
	// Types that are valid to be assigned to Message:
	//	*RunnerMessage_Ready
	//	*RunnerMessage_Result
	//	*RunnerMessage_Heartbeat
	//	*RunnerMessage_Report
	Message              isRunnerMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RunnerMessage) Reset()         { *m = RunnerMessage{} }
func (m *RunnerMessage) String() string { return proto.CompactTextString(m) }
func (*RunnerMessage) ProtoMessage()    {}
func (*RunnerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{21}
}

func (m *RunnerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunnerMessage.Unmarshal(m, b)
}
func (m *RunnerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunnerMessage.Marshal(b, m, deterministic)
}
func (m *RunnerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunnerMessage.Merge(m, src)
}
func (m *RunnerMessage) XXX_Size() int {
	return xxx_messageInfo_RunnerMessage.Size(m)
}
func (m *RunnerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RunnerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RunnerMessage proto.InternalMessageInfo

type isRunnerMessage_Message interface {
	isRunnerMessage_Message()
}

type RunnerMessage_Ready struct {
	Ready *RunnerReady `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type RunnerMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type RunnerMessage_Heartbeat struct {
	Heartbeat *HeartbeatMessage `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type RunnerMessage_Report struct {
	Report *ReportEntry `protobuf:"bytes,4,opt,name=report,proto3,oneof"`
}

func (*RunnerMessage_Ready) isRunnerMessage_Message() {}

func (*RunnerMessage_Result) isRunnerMessage_Message() {}

func (*RunnerMessage_Heartbeat) isRunnerMessage_Message() {}

func (*RunnerMessage_Report) isRunnerMessage_Message() {}

func (m *RunnerMessage) GetMessage() isRunnerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *RunnerMessage) GetReady() *RunnerReady {
	if x, ok := m.GetMessage().(*RunnerMessage_Ready); ok {
		return x.Ready
	}
	return nil
}

func (m *RunnerMessage) GetResult() *CommandResult {
	if x, ok := m.GetMessage().(*RunnerMessage_Result); ok {
		return x.Result
	}
	return nil
}

func (m *RunnerMessage) GetHeartbeat() *HeartbeatMessage {
	if x, ok := m.GetMessage().(*RunnerMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *RunnerMessage) GetReport() *ReportEntry {
	if x, ok := m.GetMessage().(*RunnerMessage_Report); ok {
		return x.Report
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RunnerMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RunnerMessage_Ready)(nil),
		(*RunnerMessage_Result)(nil),
		(*RunnerMessage_Heartbeat)(nil),
		(*RunnerMessage_Report)(nil),
	}
}

type RunnerReady struct {
	RunnerId             string   `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunnerReady) Reset()         { *m = RunnerReady{} }
func (m *RunnerReady) String() string { return proto.CompactTextString(m) }
func (*RunnerReady) ProtoMessage()    {}
func (*RunnerReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{22}
}

func (m *RunnerReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunnerReady.Unmarshal(m, b)
}
func (m *RunnerReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunnerReady.Marshal(b, m, deterministic)
}
func (m *RunnerReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunnerReady.Merge(m, src)
}
func (m *RunnerReady) XXX_Size() int {
	return xxx_messageInfo_RunnerReady.Size(m)
}
func (m *RunnerReady) XXX_DiscardUnknown() {
	xxx_messageInfo_RunnerReady.DiscardUnknown(m)
}

var xxx_messageInfo_RunnerReady proto.InternalMessageInfo

func (m *RunnerReady) GetRunnerId() string {
	if m != nil {
		return m.RunnerId
	}
	return ""
}

type CommandResult struct {
	CommandId            string            `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success              bool              `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CommandResult) Reset()         { *m = CommandResult{} }
func (m *CommandResult) String() string { return proto.CompactTextString(m) }
func (*CommandResult) ProtoMessage()    {}
func (*CommandResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{23}
}

func (m *CommandResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResult.Unmarshal(m, b)
}
func (m *CommandResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResult.Marshal(b, m, deterministic)
}
func (m *CommandResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResult.Merge(m, src)
}
func (m *CommandResult) XXX_Size() int {
	return xxx_messageInfo_CommandResult.Size(m)
}
func (m *CommandResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResult.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResult proto.InternalMessageInfo

func (m *CommandResult) GetCommandId() string {
	if m != nil {
		return m.CommandId
	}
	return ""
}

func (m *CommandResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CommandResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CommandResult) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type HeartbeatMessage struct {
	RunnerId             string   `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RunningVms           int32    `protobuf:"varint,3,opt,name=running_vms,json=runningVms,proto3" json:"running_vms,omitempty"`
	RunningTasks         int32    `protobuf:"varint,4,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatMessage) Reset()         { *m = HeartbeatMessage{} }
func (m *HeartbeatMessage) String() string { return proto.CompactTextString(m) }
func (*HeartbeatMessage) ProtoMessage()    {}
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{24}
}

func (m *HeartbeatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatMessage.Unmarshal(m, b)
}
func (m *HeartbeatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatMessage.Marshal(b, m, deterministic)
}
func (m *HeartbeatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatMessage.Merge(m, src)
}
func (m *HeartbeatMessage) XXX_Size() int {
	return xxx_messageInfo_HeartbeatMessage.Size(m)
}
func (m *HeartbeatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatMessage proto.InternalMessageInfo

func (m *HeartbeatMessage) GetRunnerId() string {
	if m != nil {
		return m.RunnerId
	}
	return ""
}

func (m *HeartbeatMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HeartbeatMessage) GetRunningVms() int32 {
	if m != nil {
		return m.RunningVms
	}
	return 0
}

func (m *HeartbeatMessage) GetRunningTasks() int32 {
	if m != nil {
		return m.RunningTasks
	}
	return 0
}

// Taskflow 发送给 Runner 的命令
type TaskflowCommand struct {
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//	*TaskflowCommand_CreateVm
	//	*TaskflowCommand_DeleteVm
	//	*TaskflowCommand_CreateTask
	//	*TaskflowCommand_StopTask
	Command              isTaskflowCommand_Command `protobuf_oneof:"command"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TaskflowCommand) Reset()         { *m = TaskflowCommand{} }
func (m *TaskflowCommand) String() string { return proto.CompactTextString(m) }
func (*TaskflowCommand) ProtoMessage()    {}
func (*TaskflowCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{25}
}

func (m *TaskflowCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskflowCommand.Unmarshal(m, b)
}
func (m *TaskflowCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskflowCommand.Marshal(b, m, deterministic)
}
func (m *TaskflowCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskflowCommand.Merge(m, src)
}
func (m *TaskflowCommand) XXX_Size() int {
	return xxx_messageInfo_TaskflowCommand.Size(m)
}
func (m *TaskflowCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskflowCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TaskflowCommand proto.InternalMessageInfo

func (m *TaskflowCommand) GetCommandId() string {
	if m != nil {
		return m.CommandId
	}
	return ""
}

type isTaskflowCommand_Command interface {
	isTaskflowCommand_Command()
}

type TaskflowCommand_CreateVm struct {
	CreateVm *CreateVMCommand `protobuf:"bytes,2,opt,name=create_vm,json=createVm,proto3,oneof"`
}

type TaskflowCommand_DeleteVm struct {
	DeleteVm *DeleteVMCommand `protobuf:"bytes,3,opt,name=delete_vm,json=deleteVm,proto3,oneof"`
}

type TaskflowCommand_CreateTask struct {
	CreateTask *CreateTaskCommand `protobuf:"bytes,4,opt,name=create_task,json=createTask,proto3,oneof"`
}

type TaskflowCommand_StopTask struct {
	StopTask *StopTaskCommand `protobuf:"bytes,5,opt,name=stop_task,json=stopTask,proto3,oneof"`
}

func (*TaskflowCommand_CreateVm) isTaskflowCommand_Command() {}

func (*TaskflowCommand_DeleteVm) isTaskflowCommand_Command() {}

func (*TaskflowCommand_CreateTask) isTaskflowCommand_Command() {}

func (*TaskflowCommand_StopTask) isTaskflowCommand_Command() {}

func (m *TaskflowCommand) GetCommand() isTaskflowCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *TaskflowCommand) GetCreateVm() *CreateVMCommand {
	if x, ok := m.GetCommand().(*TaskflowCommand_CreateVm); ok {
		return x.CreateVm
	}
	return nil
}

func (m *TaskflowCommand) GetDeleteVm() *DeleteVMCommand {
	if x, ok := m.GetCommand().(*TaskflowCommand_DeleteVm); ok {
		return x.DeleteVm
	}
	return nil
}

func (m *TaskflowCommand) GetCreateTask() *CreateTaskCommand {
	if x, ok := m.GetCommand().(*TaskflowCommand_CreateTask); ok {
		return x.CreateTask
	}
	return nil
}

func (m *TaskflowCommand) GetStopTask() *StopTaskCommand {
	if x, ok := m.GetCommand().(*TaskflowCommand_StopTask); ok {
		return x.StopTask
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TaskflowCommand) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TaskflowCommand_CreateVm)(nil),
		(*TaskflowCommand_DeleteVm)(nil),
		(*TaskflowCommand_CreateTask)(nil),
		(*TaskflowCommand_StopTask)(nil),
	}
}

type CreateVMCommand struct {
	VmId                 string            `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ImageUrl             string            `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	GitUrl               string            `protobuf:"bytes,3,opt,name=git_url,json=gitUrl,proto3" json:"git_url,omitempty"`
	GitToken             string            `protobuf:"bytes,4,opt,name=git_token,json=gitToken,proto3" json:"git_token,omitempty"`
	Cores                int32             `protobuf:"varint,5,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory               int64             `protobuf:"varint,6,opt,name=memory,proto3" json:"memory,omitempty"`
	EnvVars              map[string]string `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TtlSeconds           int64             `protobuf:"varint,8,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateVMCommand) Reset()         { *m = CreateVMCommand{} }
func (m *CreateVMCommand) String() string { return proto.CompactTextString(m) }
func (*CreateVMCommand) ProtoMessage()    {}
func (*CreateVMCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{26}
}

func (m *CreateVMCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVMCommand.Unmarshal(m, b)
}
func (m *CreateVMCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVMCommand.Marshal(b, m, deterministic)
}
func (m *CreateVMCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVMCommand.Merge(m, src)
}
func (m *CreateVMCommand) XXX_Size() int {
	return xxx_messageInfo_CreateVMCommand.Size(m)
}
func (m *CreateVMCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVMCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVMCommand proto.InternalMessageInfo

func (m *CreateVMCommand) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *CreateVMCommand) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *CreateVMCommand) GetGitUrl() string {
	if m != nil {
		return m.GitUrl
	}
	return ""
}

func (m *CreateVMCommand) GetGitToken() string {
	if m != nil {
		return m.GitToken
	}
	return ""
}

func (m *CreateVMCommand) GetCores() int32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *CreateVMCommand) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *CreateVMCommand) GetEnvVars() map[string]string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *CreateVMCommand) GetTtlSeconds() int64 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

type DeleteVMCommand struct {
	VmId                 string   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVMCommand) Reset()         { *m = DeleteVMCommand{} }
func (m *DeleteVMCommand) String() string { return proto.CompactTextString(m) }
func (*DeleteVMCommand) ProtoMessage()    {}
func (*DeleteVMCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{27}
}

func (m *DeleteVMCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVMCommand.Unmarshal(m, b)
}
func (m *DeleteVMCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVMCommand.Marshal(b, m, deterministic)
}
func (m *DeleteVMCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVMCommand.Merge(m, src)
}
func (m *DeleteVMCommand) XXX_Size() int {
	return xxx_messageInfo_DeleteVMCommand.Size(m)
}
func (m *DeleteVMCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVMCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVMCommand proto.InternalMessageInfo

func (m *DeleteVMCommand) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *DeleteVMCommand) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type CreateTaskCommand struct {
	TaskId               string            `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VmId                 string            `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ContainerId          string            `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Text                 string            `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Model                string            `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey               string            `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl              string            `protobuf:"bytes,7,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	EnvVars              map[string]string `protobuf:"bytes,8,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateTaskCommand) Reset()         { *m = CreateTaskCommand{} }
func (m *CreateTaskCommand) String() string { return proto.CompactTextString(m) }
func (*CreateTaskCommand) ProtoMessage()    {}
func (*CreateTaskCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{28}
}

func (m *CreateTaskCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskCommand.Unmarshal(m, b)
}
func (m *CreateTaskCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskCommand.Marshal(b, m, deterministic)
}
func (m *CreateTaskCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskCommand.Merge(m, src)
}
func (m *CreateTaskCommand) XXX_Size() int {
	return xxx_messageInfo_CreateTaskCommand.Size(m)
}
func (m *CreateTaskCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskCommand proto.InternalMessageInfo

func (m *CreateTaskCommand) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *CreateTaskCommand) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *CreateTaskCommand) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *CreateTaskCommand) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CreateTaskCommand) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *CreateTaskCommand) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *CreateTaskCommand) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *CreateTaskCommand) GetEnvVars() map[string]string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

type StopTaskCommand struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopTaskCommand) Reset()         { *m = StopTaskCommand{} }
func (m *StopTaskCommand) String() string { return proto.CompactTextString(m) }
func (*StopTaskCommand) ProtoMessage()    {}
func (*StopTaskCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed20c9aba6d489f, []int{29}
}

func (m *StopTaskCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopTaskCommand.Unmarshal(m, b)
}
func (m *StopTaskCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopTaskCommand.Marshal(b, m, deterministic)
}
func (m *StopTaskCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopTaskCommand.Merge(m, src)
}
func (m *StopTaskCommand) XXX_Size() int {
	return xxx_messageInfo_StopTaskCommand.Size(m)
}
func (m *StopTaskCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_StopTaskCommand.DiscardUnknown(m)
}

var xxx_messageInfo_StopTaskCommand proto.InternalMessageInfo

func (m *StopTaskCommand) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "taskflow.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "taskflow.RegisterResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "taskflow.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "taskflow.HeartbeatResponse")
	proto.RegisterType((*CreateVMRequest)(nil), "taskflow.CreateVMRequest")
	proto.RegisterMapType((map[string]string)(nil), "taskflow.CreateVMRequest.EnvVarsEntry")
	proto.RegisterType((*CreateVMResponse)(nil), "taskflow.CreateVMResponse")
	proto.RegisterType((*DeleteVMRequest)(nil), "taskflow.DeleteVMRequest")
	proto.RegisterType((*DeleteVMResponse)(nil), "taskflow.DeleteVMResponse")
	proto.RegisterType((*ListVMsRequest)(nil), "taskflow.ListVMsRequest")
	proto.RegisterType((*ListVMsResponse)(nil), "taskflow.ListVMsResponse")
	proto.RegisterType((*GetVMInfoRequest)(nil), "taskflow.GetVMInfoRequest")
	proto.RegisterType((*GetVMInfoResponse)(nil), "taskflow.GetVMInfoResponse")
	proto.RegisterType((*VMInfo)(nil), "taskflow.VMInfo")
	proto.RegisterType((*CreateTaskRequest)(nil), "taskflow.CreateTaskRequest")
	proto.RegisterMapType((map[string]string)(nil), "taskflow.CreateTaskRequest.EnvVarsEntry")
	proto.RegisterType((*CreateTaskResponse)(nil), "taskflow.CreateTaskResponse")
	proto.RegisterType((*StopTaskRequest)(nil), "taskflow.StopTaskRequest")
	proto.RegisterType((*StopTaskResponse)(nil), "taskflow.StopTaskResponse")
	proto.RegisterType((*TerminalData)(nil), "taskflow.TerminalData")
	proto.RegisterType((*TerminalResize)(nil), "taskflow.TerminalResize")
	proto.RegisterType((*ReportRequest)(nil), "taskflow.ReportRequest")
	proto.RegisterType((*ReportEntry)(nil), "taskflow.ReportEntry")
	proto.RegisterType((*RunnerMessage)(nil), "taskflow.RunnerMessage")
	proto.RegisterType((*RunnerReady)(nil), "taskflow.RunnerReady")
	proto.RegisterType((*CommandResult)(nil), "taskflow.CommandResult")
	proto.RegisterMapType((map[string]string)(nil), "taskflow.CommandResult.DataEntry")
	proto.RegisterType((*HeartbeatMessage)(nil), "taskflow.HeartbeatMessage")
	proto.RegisterType((*TaskflowCommand)(nil), "taskflow.TaskflowCommand")
	proto.RegisterType((*CreateVMCommand)(nil), "taskflow.CreateVMCommand")
	proto.RegisterMapType((map[string]string)(nil), "taskflow.CreateVMCommand.EnvVarsEntry")
	proto.RegisterType((*DeleteVMCommand)(nil), "taskflow.DeleteVMCommand")
	proto.RegisterType((*CreateTaskCommand)(nil), "taskflow.CreateTaskCommand")
	proto.RegisterMapType((map[string]string)(nil), "taskflow.CreateTaskCommand.EnvVarsEntry")
	proto.RegisterType((*StopTaskCommand)(nil), "taskflow.StopTaskCommand")
}

func init() {
	proto.RegisterFile("pkg/proto/taskflow.proto", fileDescriptor_9ed20c9aba6d489f)
}

var fileDescriptor_9ed20c9aba6d489f = []byte{
	// 1459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0xae, 0xed, 0xb5, 0xfd, 0x9c, 0x34, 0xee, 0x00, 0x8d, 0xe3, 0x14, 0x91, 0x2e, 0x12,
	0x58, 0x95, 0x9a, 0x94, 0xa0, 0x42, 0x54, 0xa4, 0x42, 0x9a, 0x94, 0x26, 0x82, 0x5c, 0x36, 0xc1,
	0x07, 0x2e, 0xd6, 0xc4, 0x3b, 0x75, 0x56, 0xf1, 0xee, 0x9a, 0x9d, 0xb1, 0x4b, 0x38, 0x20, 0x71,
	0xe5, 0x8a, 0xb8, 0x73, 0xe5, 0x73, 0x70, 0xe0, 0xce, 0x27, 0xe0, 0xca, 0xb7, 0x40, 0xf3, 0x6f,
	0x67, 0xd7, 0xde, 0x4d, 0xda, 0x06, 0x89, 0x4b, 0xb2, 0xef, 0xcd, 0x9b, 0x79, 0xff, 0xdf, 0xfc,
	0xc6, 0xd0, 0x99, 0x5c, 0x8c, 0xb6, 0x27, 0x49, 0xcc, 0xe2, 0x6d, 0x86, 0xe9, 0xc5, 0x8b, 0x71,
	0xfc, 0x72, 0x4b, 0x90, 0xa8, 0xa1, 0x69, 0xf7, 0x57, 0x0b, 0x56, 0x3d, 0x32, 0x0a, 0x28, 0x23,
	0x89, 0x47, 0xbe, 0x9b, 0x12, 0xca, 0xd0, 0xdb, 0x50, 0x63, 0xf1, 0x05, 0x89, 0x3a, 0xd6, 0xa6,
	0xd5, 0x6b, 0x7a, 0x92, 0x40, 0x5d, 0x68, 0x9c, 0xc7, 0x94, 0x45, 0x38, 0x24, 0x1d, 0x5b, 0x2c,
	0xa4, 0x34, 0xba, 0x05, 0x76, 0x30, 0xe9, 0x54, 0x04, 0xd7, 0x0e, 0x26, 0xfc, 0x84, 0x61, 0x9c,
	0x10, 0xda, 0xa9, 0x6e, 0x5a, 0xbd, 0x9a, 0x27, 0x09, 0x74, 0x07, 0x9c, 0x90, 0x84, 0x71, 0x72,
	0xd9, 0xa9, 0x6d, 0x5a, 0xbd, 0x8a, 0xa7, 0x28, 0x84, 0xa0, 0xea, 0x07, 0xf4, 0xa2, 0xe3, 0x08,
	0xae, 0xf8, 0x76, 0x87, 0xd0, 0x36, 0x66, 0xd1, 0x49, 0x1c, 0x51, 0x82, 0x36, 0xa0, 0x99, 0x4c,
	0xa3, 0x88, 0x24, 0x83, 0xc0, 0x57, 0xb6, 0x35, 0x24, 0xe3, 0xc8, 0x47, 0x1d, 0xa8, 0xd3, 0xe9,
	0x70, 0x48, 0x28, 0x15, 0xd6, 0x35, 0x3c, 0x4d, 0xf2, 0x95, 0x90, 0x50, 0x8a, 0x47, 0x44, 0x59,
	0xa8, 0x49, 0xf7, 0x17, 0x0b, 0xda, 0x87, 0x04, 0x27, 0xec, 0x8c, 0x60, 0xa6, 0xbd, 0xbf, 0x52,
	0xcb, 0x5d, 0x68, 0xb2, 0x20, 0x24, 0x94, 0xe1, 0x70, 0x22, 0xf4, 0x54, 0x3c, 0xc3, 0x40, 0xef,
	0x41, 0x8b, 0x4b, 0x06, 0xd1, 0x68, 0x30, 0x0b, 0xa9, 0xd0, 0x56, 0xf3, 0x40, 0xb1, 0xfa, 0x21,
	0x45, 0xef, 0xc3, 0x8a, 0x16, 0xe0, 0x19, 0xd0, 0xf1, 0x59, 0x56, 0xcc, 0x53, 0xce, 0x73, 0x1f,
	0xc0, 0xed, 0x8c, 0x51, 0xca, 0xf7, 0x8c, 0x7b, 0x56, 0xce, 0x3d, 0xf7, 0x6f, 0x1b, 0x56, 0xf7,
	0x13, 0x82, 0x19, 0xe9, 0x1f, 0x6b, 0x1f, 0xde, 0x82, 0xda, 0x2c, 0x34, 0xf6, 0x57, 0x67, 0xe1,
	0x91, 0x8f, 0xd6, 0xa0, 0x3e, 0xa5, 0xd2, 0x2d, 0x99, 0x3f, 0x87, 0x93, 0x47, 0x3e, 0xf7, 0x38,
	0x08, 0xf1, 0x88, 0x0c, 0xa6, 0xc9, 0x58, 0x85, 0xa8, 0x21, 0x18, 0xdf, 0x24, 0x63, 0xbe, 0x6b,
	0x14, 0x30, 0xb1, 0x54, 0x95, 0xbb, 0x46, 0x01, 0xe3, 0x0b, 0x1b, 0xd0, 0xe4, 0x0b, 0xb2, 0x52,
	0x6a, 0x72, 0xd7, 0x28, 0x60, 0xa7, 0xa2, 0x58, 0xd2, 0x02, 0x70, 0x8a, 0x0b, 0xa0, 0x9e, 0x2b,
	0x80, 0x3d, 0x68, 0x90, 0x68, 0x36, 0x98, 0xe1, 0x84, 0x76, 0x1a, 0x9b, 0x95, 0x5e, 0x6b, 0xe7,
	0x83, 0xad, 0xb4, 0x62, 0xe7, 0x7c, 0xdb, 0x7a, 0x16, 0xcd, 0xfa, 0x38, 0xa1, 0xcf, 0x22, 0x96,
	0x5c, 0x7a, 0x75, 0x22, 0x29, 0x1e, 0x7a, 0xc6, 0xc6, 0x03, 0x4a, 0x86, 0x71, 0xe4, 0xd3, 0x4e,
	0x53, 0x9c, 0x0f, 0x8c, 0x8d, 0x4f, 0x24, 0xa7, 0xfb, 0x18, 0x96, 0xb3, 0x3b, 0x51, 0x1b, 0x2a,
	0x17, 0xe4, 0x52, 0x05, 0x88, 0x7f, 0x72, 0x9b, 0x67, 0x78, 0x3c, 0xd5, 0xd5, 0x2d, 0x89, 0xc7,
	0xf6, 0xae, 0xe5, 0xfe, 0x08, 0x6d, 0x63, 0x85, 0x4a, 0x48, 0x61, 0x88, 0xef, 0xc1, 0xf2, 0x30,
	0x8e, 0x18, 0x0e, 0xa2, 0x6c, 0x9c, 0x5b, 0x29, 0x2f, 0x5f, 0xa7, 0x95, 0xd2, 0x3a, 0xad, 0xe6,
	0xeb, 0x74, 0x1f, 0x56, 0x0f, 0xc8, 0x98, 0x5c, 0x9b, 0xe1, 0x5c, 0xe9, 0xda, 0xf9, 0xd2, 0x75,
	0xbf, 0x84, 0xb6, 0x39, 0xe4, 0xba, 0xaa, 0xca, 0x1a, 0x63, 0xe7, 0x8d, 0x79, 0x00, 0xb7, 0xbe,
	0x0e, 0x28, 0xeb, 0x1f, 0xd3, 0x57, 0xe9, 0x18, 0xf7, 0x11, 0xac, 0xa6, 0xe2, 0x4a, 0xab, 0x0b,
	0x15, 0xde, 0x1e, 0x96, 0xc8, 0x74, 0xdb, 0x64, 0xba, 0x7f, 0x7c, 0x14, 0xbd, 0x88, 0x3d, 0xbe,
	0xe8, 0x7e, 0x08, 0xed, 0xe7, 0x84, 0x29, 0xce, 0x15, 0x3e, 0xbb, 0x8f, 0xe0, 0x76, 0x46, 0x50,
	0x69, 0xd8, 0x04, 0x7b, 0x16, 0x0a, 0xb1, 0x22, 0x05, 0xf6, 0x2c, 0x74, 0x13, 0x70, 0x24, 0x25,
	0x66, 0x97, 0x3e, 0xd2, 0x0e, 0x5e, 0x29, 0x87, 0x77, 0xc0, 0xa1, 0x0c, 0xb3, 0x29, 0x55, 0xdd,
	0xa2, 0x28, 0xf4, 0x2e, 0xc0, 0x50, 0xd4, 0x89, 0x3f, 0xc0, 0x4c, 0x24, 0xb1, 0xe2, 0x35, 0x15,
	0x67, 0x8f, 0xb9, 0xbf, 0xd9, 0x70, 0x5b, 0xd6, 0x11, 0x6f, 0x74, 0xed, 0xd5, 0x1a, 0xd4, 0xb9,
	0x81, 0xc6, 0x2f, 0x87, 0x93, 0x47, 0xbe, 0x71, 0xd7, 0xce, 0xa4, 0x18, 0x41, 0x95, 0x91, 0xef,
	0x99, 0x52, 0x2c, 0xbe, 0x79, 0xe1, 0x86, 0xb1, 0x4f, 0x74, 0x83, 0x4a, 0x82, 0x9f, 0x8b, 0x27,
	0xc1, 0x80, 0x17, 0xb9, 0xec, 0x4e, 0x07, 0x4f, 0x82, 0xaf, 0xc8, 0x25, 0x5a, 0x87, 0xc6, 0x19,
	0xa6, 0xb2, 0xdb, 0x1d, 0x99, 0x5b, 0x4e, 0xf3, 0x9e, 0xde, 0xcf, 0x34, 0x62, 0x5d, 0xa4, 0xa7,
	0x37, 0xdf, 0x88, 0x19, 0xd3, 0x8b, 0x5b, 0xf1, 0x46, 0x9d, 0x76, 0x08, 0x28, 0xab, 0xe6, 0x06,
	0x65, 0xfa, 0x39, 0xac, 0x9e, 0xb0, 0x78, 0xf2, 0xc6, 0x91, 0xe6, 0xfd, 0x62, 0x0e, 0xb8, 0x81,
	0x21, 0x3f, 0x5b, 0xb0, 0x7c, 0x4a, 0x92, 0x30, 0x88, 0xf0, 0xf8, 0x00, 0x33, 0x5c, 0xdc, 0xba,
	0x7c, 0x7e, 0x29, 0x21, 0x63, 0x08, 0x68, 0x96, 0x4c, 0xbc, 0x8f, 0x19, 0x16, 0x89, 0x5f, 0xf6,
	0xc4, 0x37, 0x7a, 0x08, 0x4e, 0x42, 0x68, 0xf0, 0x83, 0x1c, 0x18, 0xad, 0x9d, 0x8e, 0x49, 0x96,
	0xd6, 0xe8, 0x89, 0x75, 0x4f, 0xc9, 0xb9, 0xbb, 0x70, 0x2b, 0xbf, 0xc2, 0xcf, 0x1d, 0xc6, 0x63,
	0xe9, 0xcf, 0x8a, 0x27, 0xbe, 0x39, 0x2f, 0x89, 0x5f, 0xca, 0x8b, 0x74, 0xc5, 0x13, 0xdf, 0x6e,
	0x0f, 0x56, 0x3c, 0x32, 0x89, 0x13, 0x76, 0x5d, 0x34, 0xdd, 0x09, 0xb4, 0xa4, 0xa4, 0x4c, 0x7f,
	0x69, 0xd4, 0x79, 0x17, 0xc5, 0xd3, 0x64, 0xa8, 0x23, 0xa6, 0xa8, 0xfc, 0x1d, 0x5b, 0x99, 0xbf,
	0x63, 0x75, 0x1c, 0xaa, 0x26, 0x0e, 0xee, 0x3f, 0x16, 0xac, 0x78, 0x62, 0xe0, 0x1c, 0xcb, 0xa0,
	0xa3, 0x07, 0x50, 0x4b, 0x08, 0xf6, 0x2f, 0xd5, 0x0c, 0x78, 0xc7, 0x04, 0x46, 0xca, 0x79, 0x7c,
	0xf1, 0x70, 0xc9, 0x93, 0x52, 0xe8, 0x23, 0x11, 0xc8, 0xe9, 0x98, 0x09, 0x53, 0x5a, 0x3b, 0x6b,
	0x99, 0xaa, 0x8f, 0xc3, 0x10, 0x47, 0xbe, 0x27, 0x96, 0x0f, 0x97, 0x3c, 0x25, 0x88, 0x1e, 0x43,
	0xf3, 0x5c, 0xdf, 0xd2, 0xc2, 0xca, 0xd6, 0x4e, 0xd7, 0xec, 0x4a, 0x2f, 0x70, 0x65, 0xd0, 0xe1,
	0x92, 0x67, 0xc4, 0xd1, 0x36, 0x57, 0xc7, 0x23, 0xa4, 0xf2, 0x96, 0x35, 0xcf, 0x44, 0x4e, 0x2a,
	0xe3, 0xe4, 0xd3, 0x66, 0x5a, 0x5d, 0xee, 0x7d, 0x68, 0x65, 0x5c, 0xb8, 0x7a, 0xf6, 0xfe, 0x65,
	0xc1, 0x4a, 0xce, 0x7e, 0x31, 0xa1, 0x24, 0xc3, 0xc8, 0x37, 0x15, 0xe7, 0xcd, 0x40, 0x14, 0x7a,
	0x94, 0x26, 0x84, 0xcf, 0x8b, 0x7b, 0x25, 0x91, 0xdb, 0xe2, 0xa5, 0x2f, 0x07, 0x85, 0x10, 0xef,
	0x7e, 0x0a, 0xcd, 0x94, 0xf5, 0x5a, 0x23, 0x22, 0x07, 0xda, 0x74, 0xbe, 0xff, 0x77, 0xd0, 0xf6,
	0xbb, 0x0d, 0xab, 0xa7, 0xca, 0x73, 0xe5, 0xf8, 0x75, 0xc1, 0xde, 0x05, 0x75, 0x37, 0x0c, 0x66,
	0xa1, 0xaa, 0xbb, 0xf5, 0x45, 0xd8, 0xa3, 0x0e, 0x3b, 0x5c, 0xf2, 0x1a, 0x52, 0xba, 0x1f, 0xf2,
	0x9d, 0xbe, 0xb8, 0xca, 0xf9, 0xce, 0xca, 0xfc, 0x4e, 0x7d, 0xcb, 0x67, 0x76, 0x4a, 0xe9, 0x7e,
	0x88, 0x9e, 0x40, 0x4b, 0xe9, 0xe4, 0xe2, 0xaa, 0xfc, 0x36, 0x8a, 0x66, 0xbc, 0xd9, 0xad, 0xee,
	0x34, 0xce, 0xe4, 0x9a, 0x29, 0x8b, 0x27, 0x72, 0x77, 0x6d, 0x5e, 0xb3, 0x9e, 0x97, 0x19, 0xcd,
	0x54, 0xb1, 0x78, 0x09, 0x2b, 0xd7, 0xdd, 0x3f, 0x33, 0x88, 0x55, 0xc7, 0xaa, 0x0c, 0xcf, 0x18,
	0x60, 0x6a, 0x97, 0x03, 0xd3, 0x4a, 0x39, 0x30, 0xad, 0x96, 0x01, 0xd3, 0x5a, 0x31, 0x30, 0x75,
	0x4a, 0x81, 0x69, 0xbd, 0x0c, 0x98, 0x2a, 0x17, 0x5e, 0x0d, 0x98, 0x36, 0xfe, 0x53, 0x60, 0x7a,
	0x64, 0x80, 0xe1, 0x95, 0x81, 0xbc, 0x1e, 0xd3, 0xb8, 0x7f, 0xe4, 0xc0, 0x89, 0x3e, 0xed, 0xf5,
	0xc0, 0xc9, 0xbc, 0x9a, 0xca, 0x22, 0x74, 0xd2, 0xf8, 0xa5, 0x5a, 0x84, 0x5f, 0x6a, 0x25, 0xf8,
	0xc5, 0x29, 0xc5, 0x2f, 0xf5, 0x72, 0xfc, 0xd2, 0x28, 0xc7, 0x2f, 0x57, 0x66, 0xec, 0x46, 0x09,
	0xb9, 0x6f, 0x50, 0xc7, 0x75, 0x21, 0xdc, 0xf9, 0xc9, 0xd1, 0xb7, 0xd6, 0x09, 0x49, 0x66, 0xc1,
	0x90, 0xf0, 0x72, 0xd3, 0x8f, 0x5e, 0xb4, 0x9e, 0xbd, 0x13, 0x72, 0xef, 0xf3, 0x6e, 0xb7, 0x68,
	0x49, 0x21, 0x94, 0x03, 0x68, 0xa6, 0xc3, 0x11, 0x15, 0x5d, 0x48, 0xfa, 0x90, 0x8d, 0xc2, 0x35,
	0x75, 0xca, 0x1e, 0x34, 0x74, 0x75, 0xa3, 0xf5, 0xd2, 0xa7, 0x58, 0xd6, 0x90, 0x85, 0xf7, 0xd1,
	0x1e, 0x34, 0x74, 0x69, 0xa2, 0x82, 0xe1, 0x54, 0x70, 0xc4, 0xc2, 0xeb, 0xe4, 0x09, 0xd4, 0xd5,
	0xd3, 0x01, 0x65, 0x90, 0x4d, 0xfe, 0xf1, 0xd1, 0x5d, 0x2f, 0x58, 0x31, 0xb1, 0x48, 0x9f, 0x06,
	0xd9, 0x58, 0xcc, 0x3f, 0x2c, 0xb2, 0xb1, 0x58, 0x7c, 0x4b, 0x3c, 0x07, 0x30, 0x95, 0x83, 0x36,
	0xae, 0xc0, 0xc3, 0xdd, 0xbb, 0xc5, 0x8b, 0x26, 0x22, 0xba, 0x36, 0x50, 0xc1, 0xd0, 0x2c, 0x88,
	0xc8, 0x02, 0xfe, 0x3c, 0x30, 0xf0, 0xed, 0x84, 0x25, 0x04, 0x87, 0xe8, 0xce, 0x22, 0xe4, 0xe3,
	0xd7, 0x6a, 0xb7, 0x84, 0xdf, 0xb3, 0x1e, 0x5a, 0xe8, 0x0b, 0x58, 0x96, 0x30, 0x43, 0x9d, 0xb1,
	0x36, 0x0f, 0x3f, 0xb4, 0x29, 0xc5, 0xb8, 0xe4, 0xa1, 0x85, 0x9e, 0xa7, 0xb8, 0xa2, 0xe0, 0x88,
	0x2c, 0x10, 0xcb, 0xa6, 0x67, 0xee, 0x7a, 0xe4, 0xa6, 0x3c, 0xdd, 0xfd, 0xf6, 0x93, 0x51, 0xc0,
	0xce, 0xa7, 0x67, 0x5b, 0xc3, 0x38, 0xdc, 0x1e, 0x9e, 0xe3, 0x80, 0x05, 0xd1, 0xf6, 0x71, 0x1c,
	0x5d, 0x90, 0xcb, 0xfd, 0xd8, 0x27, 0xe9, 0x0f, 0x57, 0xdb, 0xe9, 0x6f, 0x59, 0x9f, 0x89, 0xbf,
	0x67, 0x8e, 0xf8, 0xf7, 0xf1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0xb8, 0xcd, 0xad, 0xe5,
	0x12, 0x00, 0x00,
}
